name: Fix Site
on: workflow_dispatch
jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fix opacity
        run: |
          sed -i 's/opacity:0;transform:translateY(18px)/opacity:1;transform:translateY(0px)/g' index.html
          echo "Done!"
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix blank sections
